### ISSUE TITLE
Running Deep Polynomial Regression

### ISSUE THREAD

**Issue by Teja10** [yutaekoh/LaneLineDetection#1]
Get model running and working on a sample dataset.

**Comment by juuwong** [comment]
Testing commit hash:
[adding PolyLaneNet submodule](https://github.com/yutaekoh/LaneLineDetection/commit/6b30d4ebcdce8c8718ed645b2a8c3e82e94b3958)

issue resolved, awaiting verification: @Teja10

**Comment by juuwong** [comment]
Testing commit hash #2:
#6b30d4ebcdce8c8718ed645b2a8c3e82e94b3958
